twitter:
  user_search_limit: 50
  num_tweets_per_user: 100
  store_path: "data/raw/twitter_data.csv"
  keywords:
    - "web3"
    - "blockchain"
    - "ethereum"
    - "decentralized"
    - "crypto"
    - "nft"
    - "metaverse"
    - "defi"
    - "dapp"
    - "smart contract"
    - "solidity"
    - "web3js"
    - "ipfs"
    - "dao"
    - "erc20"
    - "erc721"
    - "erc1155"
    - "eth"
    - "btc"
    - "solana"
    - "avalanche"
    - "polygon"
    - "matic"
    - "binance"
    - "bsc"
    - "cosmos"
    - "terra"
    - "polkadot"
    - "substrate"
    - "kusama"
    - "tezos"
    - "cardano"
    - "algorand"
    - "hedera"
    - "hashgraph"
    - "filecoin"
    - "siacoin"
    - "storj"
    - "arweave"
    - "skynet"
    - "handshake"
    - "unstoppable"
    - "ens"
    - "ipns"
    - "ipfs"
    - "dat"