kafka:
  bootstrap_servers:
    - "localhost:29092"
    - "localhost:29093"

  topics:
    tweet_topic: "twitter_tweets"
    user_topic: "twitter_users"
    mention_topic: "twitter_mentions"
    
  consumer_config:
    group_id: "twitter_group"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    
  producer_config:
    acks: 1
    retries: 3
    batch_size: 16384
    linger_ms: 1
    buffer_memory: 33554432